import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import { NavigationMenuDemo } from "./_components/Navbar/Navbar";
import Footer from "./_components/Footer/Footer";
import { Toaster } from "@/components/ui/sonner";
import WrapperComponent from "./_components/WrapperComponent/WrapperComponent";
import TanStakeProvider from "@/providers/TanStakeProvider";

const exo = Exo({
  subsets: ["latin"],
  weight: ["400", "500",],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={exo.className}
      >
        <TanStakeProvider>
          <WrapperComponent>
            <NavigationMenuDemo/>
          </WrapperComponent>
        {children}
        <Toaster position="top-right"/>
        <Footer/>
        </TanStakeProvider>
      </body>
    </html>
  );
}
